<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Blog;
use App\Models\DesignTier;
use App\Models\Faq;
use App\Models\Portfolio;
use App\Models\PricingPlan;
use App\Models\ProcessStep;
use App\Models\Service;
use App\Models\ServiceFeature;
use App\Models\SiteSetting;
use App\Models\Testimonial;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Admin
        Admin::truncate();
        Admin::create([
            'username' => 'admin',
            'password' => Hash::make('admin123'),
            'name' => 'Administrator JuangDev',
            'role' => 'admin',
        ]);

        // 2. Site Settings
        SiteSetting::truncate();
        $settings = [
            'site_name' => 'JuangDev',
            'site_tagline' => 'Jasa Pembuatan Website & Aplikasi Web Profesional',
            'site_description' => 'Solusi pembuatan website murah berkualitas tinggi dengan teknologi modern.',
            'whatsapp_number' => '62859171681988',
            'email' => 'halo@juangdev.com',
            'phone' => '+62 812-3456-7890',
            'address' => 'Jakarta, Indonesia',
            'working_hours' => 'Senin - Sabtu: 09:00 - 18:00 WIB',
            'instagram_url' => 'https://instagram.com/juangdev',
            'x_url' => 'https://x.com/juangdev',
            'threads_url' => 'https://threads.net/@juangdev',
            'github_url' => 'https://github.com/juangdev',
            'linkedin_url' => 'https://linkedin.com/company/juangdev',
            'tiktok_url' => '',
            'feature_showcase_badge' => 'Enterprise & Custom Build',
            'feature_showcase_title' => 'Pengembangan Website & Sistem Modern',
            'feature_showcase_desc' => 'Solusi website dan aplikasi web internal yang cepat, aman, responsif di seluruh perangkat, dan mudah dikelola.',
            'feature_showcase_price' => 'Rp 999.000',
            'feature_showcase_point1_title' => 'Antarmuka User-Friendly & Responsif',
            'feature_showcase_point1_desc' => 'Desain UI/UX intuitif yang optimal di layar laptop maupun smartphone.',
            'feature_showcase_point2_title' => 'Performa Cepat & Stabil',
            'feature_showcase_point2_desc' => 'Arsitektur modern dan efisien untuk menjamin sistem berjalan mulus tanpa lag.',
            'feature_showcase_point3_title' => 'Keamanan Data Terjamin',
            'feature_showcase_point3_desc' => 'Enkripsi SSL dan proteksi data berlapis untuk menjaga transaksi bisnis Anda.',
            'feature_showcase_point4_title' => 'Dashboard & Manajemen Terintegrasi',
            'feature_showcase_point4_desc' => 'Kemudahan mengelola konten dan melihat laporan performa secara terpusat.',
            'feature_showcase_image' => '/services-laptop.jpg',
        ];
        foreach ($settings as $k => $v) {
            SiteSetting::create(['key' => $k, 'value' => $v]);
        }

        // 3. Services
        Service::truncate();
        $services = [
            [
                'id' => 1,
                'slug' => 'landing-page',
                'name' => 'Landing Page',
                'tagline' => 'Maksimalkan Konversi Penjualan',
                'description' => 'Halaman web tunggal yang dioptimasi secara khusus untuk memaksimalkan konversi pemasaran bisnis Anda.',
                'icon' => 'globe',
                'base_price' => 99000,
                'starting_price' => '99K',
                'delivery_time' => '2-3 Hari',
                'popular' => false,
                'features' => ['Desain Responsif', 'SEO Basic', 'Mobile Friendly', 'Call to Action Optimal', 'Setup Domain & Hosting'],
                'technologies' => ['HTML5', 'Tailwind CSS', 'Alpine.js', 'Next.js'],
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'slug' => 'company-profile',
                'name' => 'Company Profile',
                'tagline' => 'Tingkatkan Kredibilitas Bisnis',
                'description' => 'Website profesional dan elegan untuk membangun kredibilitas serta menampilkan identitas bisnis Anda ke publik.',
                'icon' => 'monitor',
                'base_price' => 199000,
                'starting_price' => '199K',
                'delivery_time' => '3-5 Hari',
                'popular' => true,
                'features' => ['Hingga 5 Halaman', 'Galeri Portfolio', 'Form Kontak Interaktif', 'SEO Friendly', 'Integrasi Google Maps'],
                'technologies' => ['Laravel', 'Blade', 'Tailwind CSS', 'MySQL'],
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'slug' => 'ecommerce',
                'name' => 'E-Commerce',
                'tagline' => 'Jual Produk Online 24/7',
                'description' => 'Toko online modern dengan sistem belanja terstruktur, lengkap dengan katalog produk dan checkout.',
                'icon' => 'shopping-bag',
                'base_price' => 499000,
                'starting_price' => '499K',
                'delivery_time' => '5-7 Hari',
                'popular' => false,
                'features' => ['Katalog Produk', 'Keranjang Belanja', 'Integrasi WA Checkout', 'Payment Gateway (Opsional)', 'Dashboard Penjualan'],
                'technologies' => ['Laravel', 'Vue.js', 'MySQL', 'Midtrans'],
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'id' => 4,
                'slug' => 'sistem-informasi',
                'name' => 'Sistem Informasi',
                'tagline' => 'Digitalisasi Operasional Bisnis',
                'description' => 'Sistem digitalisasi pendataan dan pelaporan untuk mempermudah operasional internal perusahaan Anda.',
                'icon' => 'bot',
                'base_price' => 399000,
                'starting_price' => '399K',
                'delivery_time' => '7-14 Hari',
                'popular' => false,
                'features' => ['Manajemen Data Terpadu', 'Dashboard Analitik Visual', 'Export Laporan PDF/Excel', 'Hak Akses Multi-Level', 'Cloud Backup'],
                'technologies' => ['Laravel', 'Alpine.js', 'MySQL', 'Tailwind CSS'],
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'id' => 5,
                'slug' => 'custom-app',
                'name' => 'Custom Web App',
                'tagline' => 'Aplikasi Sesuai Kebutuhan Spesifik',
                'description' => 'Pengembangan aplikasi web khusus dengan fitur kompleks yang dirancang mengikuti alur bisnis unik Anda.',
                'icon' => 'palette',
                'base_price' => 199000,
                'starting_price' => '199K',
                'delivery_time' => '7-21 Hari',
                'popular' => false,
                'features' => ['Desain UI/UX Custom Eksklusif', 'API Integration & Webhook', 'Sistem Login & Role Bertingkat', 'Skalabilitas Tinggi', 'Garansi & Maintenance'],
                'technologies' => ['Laravel', 'Next.js', 'Node.js', 'PostgreSQL', 'Docker'],
                'display_order' => 5,
                'is_active' => true,
            ],
        ];
        foreach ($services as $srv) {
            Service::create($srv);
        }

        // 4. Service Features (Add-ons for Estimator)
        ServiceFeature::truncate();
        $features = [
            [
                'id' => 1,
                'title' => 'Optimasi SEO Lanjutan',
                'description' => 'Optimasi mesin pencari mendalam agar website mudah ditemukan di halaman utama Google.',
                'category' => 'addon',
                'price' => 500000,
                'popular' => true,
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'title' => 'Payment Gateway Otomatis',
                'description' => 'Integrasi pembayaran otomatis QRIS, Transfer Bank, Kartu Kredit, dan E-Wallet.',
                'category' => 'addon',
                'price' => 800000,
                'popular' => true,
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'title' => 'Dukungan Multi-Bahasa',
                'description' => 'Dukungan multi-bahasa (Bahasa Indonesia & Bahasa Inggris) dengan pemindah bahasa yang mudah.',
                'category' => 'addon',
                'price' => 1200000,
                'popular' => false,
                'display_order' => 3,
                'is_active' => true,
            ],
        ];
        foreach ($features as $f) {
            ServiceFeature::create($f);
        }

        // 5. Design Tiers (for Estimator)
        DesignTier::truncate();
        $tiers = [
            [
                'id' => 1,
                'name' => 'Putih Bersih (Standar)',
                'tagline' => 'Minimalis & Bersih',
                'description' => 'Tampilan profesional yang bersih, modern, dan nyaman dibaca pengunjung.',
                'price' => 0,
                'badge' => 'Termasuk',
                'features' => ['Tata Letak Bersih', 'Tipografi Standar', 'Optimasi Seluler'],
                'is_popular' => false,
                'display_order' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Biru Gelap (Pro)',
                'tagline' => 'Mode Gelap Elegan',
                'description' => 'Desain gelap elegan bernuansa teknologi modern dengan aksen biru profesional.',
                'price' => 1500000,
                'badge' => 'Populer',
                'features' => ['Tampilan Mode Gelap', 'Mikro-Interaksi', 'Grafis Kustom', 'Tipografi Premium'],
                'is_popular' => true,
                'display_order' => 2,
            ],
            [
                'id' => 3,
                'name' => 'Hijau Neon (Premium)',
                'tagline' => 'Futuristik & Modern',
                'description' => 'Desain futuristik dengan efek glassmorphism, glowing neon, dan animasi halus berkualitas tinggi.',
                'price' => 3500000,
                'badge' => 'Premium',
                'features' => ['Antarmuka Futuristik', 'Efek Glassmorphism', 'Gerakan Interaktif GSAP', 'Ikon Kustom Eksklusif'],
                'is_popular' => false,
                'display_order' => 3,
            ],
        ];
        foreach ($tiers as $dt) {
            DesignTier::create($dt);
        }

        // 6. Pricing Plans (All 15 plans across 5 categories)
        PricingPlan::truncate();
        $plans = [
            // Landing Page
            [
                'id' => 1,
                'category' => 'landing-page',
                'name' => 'Basic',
                'badge' => null,
                'price' => '99k',
                'period' => 'proyek',
                'description' => 'Sempurna untuk validasi ide & produk tunggal',
                'features' => ['1 Halaman Landing Page', 'Desain Template Premium', 'Mobile Responsive', 'Tombol WhatsApp', 'Waktu Pengerjaan 2 Hari'],
                'not_included' => ['Custom Desain dari Nol', 'SEO Advanced', 'Multi Bahasa'],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=landing-basic',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'category' => 'landing-page',
                'name' => 'Rekomendasi',
                'badge' => 'PALING POPULER',
                'price' => '299k',
                'period' => 'proyek',
                'description' => 'Pilihan terbaik untuk konversi marketing',
                'features' => ['Desain UI/UX Custom', 'Copywriting Persuasif', 'Integrasi Google Analytics', 'Setup Domain & Hosting', 'Waktu Pengerjaan 5 Hari'],
                'not_included' => ['Multi Bahasa'],
                'popular' => true,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=landing-rekomendasi',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'category' => 'landing-page',
                'name' => 'Premium',
                'badge' => null,
                'price' => '499k',
                'period' => 'proyek',
                'description' => 'Desain kompleks dengan animasi interaktif',
                'features' => ['Animasi Interaktif (GSAP)', 'A/B Testing Setup', 'Integrasi Email Marketing', 'Prioritas Support', 'Waktu Pengerjaan 7 Hari'],
                'not_included' => [],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=landing-premium',
                'display_order' => 3,
                'is_active' => true,
            ],

            // Company Profile
            [
                'id' => 4,
                'category' => 'company-profile',
                'name' => 'Basic',
                'badge' => null,
                'price' => '199k',
                'period' => 'proyek',
                'description' => 'Profil bisnis profesional & elegan',
                'features' => ['Maksimal 3 Halaman', 'Desain Responsif', 'Form Kontak', 'Galeri Foto', 'Waktu Pengerjaan 3 Hari'],
                'not_included' => ['CMS Admin Update', 'Multi Bahasa'],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=company-basic',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'id' => 5,
                'category' => 'company-profile',
                'name' => 'Rekomendasi',
                'badge' => 'PALING POPULER',
                'price' => '499k',
                'period' => 'proyek',
                'description' => 'Tampil meyakinkan di mata klien',
                'features' => ['Hingga 7 Halaman', 'Desain UI/UX Custom', 'CMS untuk Update Konten', 'SEO Basic Setup', 'Waktu Pengerjaan 7 Hari'],
                'not_included' => ['Multi Bahasa'],
                'popular' => true,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=company-rekomendasi',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'id' => 6,
                'category' => 'company-profile',
                'name' => 'Premium',
                'badge' => null,
                'price' => '899k',
                'period' => 'proyek',
                'description' => 'Untuk perusahaan berskala besar',
                'features' => ['Halaman Tak Terbatas', 'Multi-bahasa (Bilingual)', 'Portal Karir', 'Integrasi Sistem Internal', 'Waktu Pengerjaan 14 Hari'],
                'not_included' => [],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=company-premium',
                'display_order' => 6,
                'is_active' => true,
            ],

            // E-Commerce
            [
                'id' => 7,
                'category' => 'ecommerce',
                'name' => 'Basic',
                'badge' => null,
                'price' => '499k',
                'period' => 'proyek',
                'description' => 'Mulai jualan online dengan cepat',
                'features' => ['Katalog hingga 50 Produk', 'Keranjang Belanja', 'Integrasi WhatsApp Checkout', 'Desain Mobile Friendly'],
                'not_included' => ['Payment Gateway Otomatis', 'Hitung Ongkir Otomatis'],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=ecommerce-basic',
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'id' => 8,
                'category' => 'ecommerce',
                'name' => 'Rekomendasi',
                'badge' => 'PALING POPULER',
                'price' => '899k',
                'period' => 'proyek',
                'description' => 'Toko online otomatis & scalable',
                'features' => ['Produk Tak Terbatas', 'Payment Gateway Integrasi', 'Perhitungan Ongkir Otomatis', 'Manajemen Inventaris', 'Dashboard Analitik'],
                'not_included' => ['Multi Vendor'],
                'popular' => true,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=ecommerce-rekomendasi',
                'display_order' => 8,
                'is_active' => true,
            ],
            [
                'id' => 9,
                'category' => 'ecommerce',
                'name' => 'Premium',
                'badge' => null,
                'price' => '999k',
                'period' => 'proyek',
                'description' => 'Sistem toko online kompleks & custom',
                'features' => ['Multi-vendor Setup', 'Sistem Poin/Diskon', 'Integrasi POS Internal', 'Aplikasi Mobile WebView', 'Dukungan Prioritas 24/7'],
                'not_included' => [],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=ecommerce-premium',
                'display_order' => 9,
                'is_active' => true,
            ],

            // Sistem Informasi
            [
                'id' => 10,
                'category' => 'sistem-informasi',
                'name' => 'Basic',
                'badge' => null,
                'price' => '399k',
                'period' => 'proyek',
                'description' => 'Aplikasi web internal sederhana',
                'features' => ['Modul Login/Register', 'CRUD Data Basic', 'Export PDF/Excel', 'Database Setup'],
                'not_included' => ['Multi-Role Bertingkat', 'API External'],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=sistem-basic',
                'display_order' => 10,
                'is_active' => true,
            ],
            [
                'id' => 11,
                'category' => 'sistem-informasi',
                'name' => 'Rekomendasi',
                'badge' => 'PALING POPULER',
                'price' => '799k',
                'period' => 'proyek',
                'description' => 'Sistem operasional lengkap & aman',
                'features' => ['Multi-role Akses (Admin/User)', 'Dashboard Analitik', 'Notifikasi Email/WA', 'API Integration', 'Setup Cloud Server'],
                'not_included' => ['Microservices SLA'],
                'popular' => true,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=sistem-rekomendasi',
                'display_order' => 11,
                'is_active' => true,
            ],
            [
                'id' => 12,
                'category' => 'sistem-informasi',
                'name' => 'Premium',
                'badge' => null,
                'price' => '999k',
                'period' => 'proyek',
                'description' => 'Sistem ERP/CRM skala perusahaan',
                'features' => ['Modul Tak Terbatas', 'Arsitektur Microservices', 'Keamanan Tingkat Tinggi', 'SLA Guarantee 99.9%', 'Maintenance 6 Bulan'],
                'not_included' => [],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=sistem-premium',
                'display_order' => 12,
                'is_active' => true,
            ],

            // Custom Web App
            [
                'id' => 13,
                'category' => 'custom-app',
                'name' => 'Basic',
                'badge' => null,
                'price' => '199k - 599k',
                'period' => 'proyek',
                'description' => 'Pilihan 1 layanan apa saja (Landing Page / Compro / Toko Online / Sistem) dengan kustomisasi modul dasar',
                'features' => ['Bebas Pilih 1 Layanan Apapun', 'Kustomisasi 1-3 Modul Spesifik', 'Desain UI/UX Responsif & Modern', 'Integrasi WhatsApp & Form Kontak', 'Setup Domain & Hosting Standar'],
                'not_included' => ['Realtime WebSockets', 'Dedicated Microservices'],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=custom-basic',
                'display_order' => 13,
                'is_active' => true,
            ],
            [
                'id' => 14,
                'category' => 'custom-app',
                'name' => 'Rekomendasi',
                'badge' => 'PALING POPULER',
                'price' => '399k - 999k',
                'period' => 'proyek',
                'description' => 'Pilihan 1 layanan apa saja (Landing Page / Compro / Toko Online / Sistem) dengan fitur lengkap & admin CMS',
                'features' => ['Bebas Pilih 1 Layanan Apapun', 'Integrasi Dashboard Admin & CMS Kustom', 'Kustomisasi Modul & Hak Akses Multi-Role', 'Fitur Notifikasi & API Integrasi', 'Garansi & Prioritas Support'],
                'not_included' => [],
                'popular' => true,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=custom-rekomendasi',
                'display_order' => 14,
                'is_active' => true,
            ],
            [
                'id' => 15,
                'category' => 'custom-app',
                'name' => 'Premium',
                'badge' => null,
                'price' => '599k - 1.099k',
                'period' => 'proyek',
                'description' => 'Pilihan 1 layanan apa saja (Landing Page / Compro / Toko Online / Sistem) dengan arsitektur full-custom dari nol',
                'features' => ['Bebas Pilih 1 Layanan Apapun (Full-Custom)', 'Kustomisasi Arsitektur Enterprise dari Nol', 'Arsitektur Skalabilitas Tinggi & Cloud Server', 'Payment Gateway, Webhook & Keamanan Enkripsi', 'Maintenance Berkala & Support Eksklusif 24/7'],
                'not_included' => [],
                'popular' => false,
                'cta_text' => 'Pilih Paket',
                'cta_href' => '/contact?plan=custom-premium',
                'display_order' => 15,
                'is_active' => true,
            ],
        ];
        foreach ($plans as $p) {
            PricingPlan::create($p);
        }

        // 7. Portfolios (8 items)
        Portfolio::truncate();
        $portfolios = [
            [
                'id' => 1,
                'slug' => 'property-management-app',
                'title' => 'Property Management App',
                'client' => 'Kos Pangeran & Landlord Group',
                'client_industry' => 'Property, Landlord, and Rental',
                'duration' => 'Januari 2024 - Juni 2024 (6 Bulan)',
                'category' => 'Custom Web App',
                'description' => 'Aplikasi pengelolaan properti lengkap untuk membantu pemilik properti mengelola kontrakan, apartemen, atau rumah kos dengan mudah dan efisien.',
                'overview' => 'Full management apps in website to help homeowner to manage their property like house-rental, apartment, or boarding house. Designed to be simple and easy to use, Kos Pangeran is a perfect solution for those who want to manage their property without any hassle.',
                'key_features' => [
                    'Property & Room Management',
                    'Member & Tenant Management',
                    'Payment & Transaction System',
                    'Reporting & Data Export'
                ],
                'gallery' => [
                    ['title' => 'Property & Room Management', 'image_url' => '/uploads/1781526251754-169158715-9.png'],
                    ['title' => 'Member & Tenant Management', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                    ['title' => 'Payment & Transaction System', 'image_url' => '/uploads/1781526529261-225644737-11.png'],
                    ['title' => 'Reporting & Data Export', 'image_url' => '/uploads/1781526616429-46906960-12.png'],
                ],
                'image_url' => '/uploads/1781526860110-978453413-15.png',
                'live_url' => 'https://demo.juangdev.com/property-app',
                'technologies' => ['Laravel', 'MongoDB', 'Bootstrap', 'Tailwind CSS'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 3,
                'package_tier' => 'Rekomendasi',
                'display_order' => 1,
            ],
            [
                'id' => 2,
                'slug' => 'healthcare-erp',
                'title' => 'Healthcare & Klinik ERP',
                'client' => 'PT Medika Nusantara',
                'client_industry' => 'Healthcare & Medical Industry',
                'duration' => 'Februari 2024 - Mei 2024 (4 Bulan)',
                'category' => 'Sistem Informasi',
                'description' => 'Sistem manajemen rumah sakit terpadu lengkap dengan pendaftaran pasien, penjadwalan janji medis, tagihan otomatis, dan manajemen apotek.',
                'overview' => 'Sistem informasi manajemen kesehatan (SIMRS) komprehensif yang mengintegrasikan alur kerja pendaftaran pasien, rekam medis elektronik, antrean dokter, farmasi, dan billing tagihan rumah sakit secara realtime.',
                'key_features' => [
                    'Manajemen Antrean & Rekam Medis Digital',
                    'Integrasi Sistem Farmasi & Inventaris Obat',
                    'Kasir & Billing Tagihan Pasien Otomatis',
                    'Dashboard Laporan Operasional Rumah Sakit'
                ],
                'gallery' => [
                    ['title' => 'Dashboard Rekam Medis', 'image_url' => '/uploads/1781526251754-169158715-9.png'],
                    ['title' => 'Manajemen Antrean Pasien', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                    ['title' => 'Sistem Farmasi & Kasir', 'image_url' => '/uploads/1781526703401-819330083-13.png'],
                    ['title' => 'Laporan Analitik Medis', 'image_url' => '/uploads/1781527358962-872605838-15.png'],
                ],
                'image_url' => '/uploads/1781526251754-169158715-9.png',
                'live_url' => 'https://demo.juangdev.com/healthcare',
                'technologies' => ['Laravel', 'Blade', 'MySQL', 'Tailwind CSS', 'Docker'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 1,
                'package_tier' => 'Premium',
                'display_order' => 2,
            ],
            [
                'id' => 3,
                'slug' => 'school-management-system',
                'title' => 'Sistem Informasi Sekolah Digital',
                'client' => 'Yayasan Pendidikan Maju',
                'client_industry' => 'Education & E-Learning',
                'duration' => 'Maret 2024 - Juli 2024 (5 Bulan)',
                'category' => 'Sistem Informasi',
                'description' => 'Platform manajemen sekolah terpadu yang menangani pendaftaran siswa, penilaian akademis, presensi digital, dan komunikasi orang tua.',
                'overview' => 'Platform sekolah pintar (Smart Campus) yang dirancang untuk mempermudah tata kelola akademis, pembagian nilai, pembayaran SPP online, serta portal komunikasi terpadu untuk orang tua dan guru.',
                'key_features' => [
                    'PPDB & Portal Akademik Siswa',
                    'Presensi Digital & Rekap Nilai Rapor',
                    'Payment Gateway Pembayaran SPP',
                    'Notifikasi WhatsApp Otomatis Ke Orang Tua'
                ],
                'gallery' => [
                    ['title' => 'Portal Nilai & Rapor', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                    ['title' => 'Dashboard Pendaftaran PPDB', 'image_url' => '/uploads/1781526529261-225644737-11.png'],
                    ['title' => 'Pembayaran SPP Online', 'image_url' => '/uploads/1781526616429-46906960-12.png'],
                    ['title' => 'Presensi & Kehadiran', 'image_url' => '/uploads/1781526786919-43514709-14.png'],
                ],
                'image_url' => '/uploads/1781526353116-173345013-10.png',
                'live_url' => 'https://demo.juangdev.com/school',
                'technologies' => ['Laravel', 'Vue.js', 'MySQL', 'Redis'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 2,
                'package_tier' => 'Rekomendasi',
                'display_order' => 3,
            ],
            [
                'id' => 4,
                'slug' => 'property-marketplace',
                'title' => 'Marketplace Properti Real Estate',
                'client' => 'PropertyKu Indonesia',
                'client_industry' => 'Real Estate & Brokerage',
                'duration' => 'Agustus 2023 - Desember 2023 (5 Bulan)',
                'category' => 'E-Commerce',
                'description' => 'Platform direktori properti real estate dengan fitur pencarian lanjutan, tur virtual 360, dan kalkulator KPR terintegrasi.',
                'overview' => 'Website portal jual beli properti modern yang menghubungkan agen properti, pengembang, dan pembeli. Dilengkapi peta interaktif Google Maps, filter harga, simulasi KPR, dan pesan langsung via WhatsApp.',
                'key_features' => [
                    'Filter Pencarian Properti Canggih',
                    'Simulasi Kalkulator KPR Interaktif',
                    'Integrasi Peta & Lokasi Properti',
                    'Manajemen Listing Agen & Developer'
                ],
                'gallery' => [
                    ['title' => 'Pencarian Properti Interaktif', 'image_url' => '/uploads/1781526529261-225644737-11.png'],
                    ['title' => 'Detail Halaman Unit Properti', 'image_url' => '/uploads/1781526860110-978453413-15.png'],
                    ['title' => 'Kalkulator KPR', 'image_url' => '/uploads/1781526941397-658466739-16.png'],
                    ['title' => 'Dashboard Agen Properti', 'image_url' => '/uploads/1781527358962-872605838-15.png'],
                ],
                'image_url' => '/uploads/1781526529261-225644737-11.png',
                'live_url' => 'https://demo.juangdev.com/property',
                'technologies' => ['Next.js', 'Laravel API', 'PostgreSQL', 'AWS'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 1,
                'package_tier' => 'Rekomendasi',
                'display_order' => 4,
            ],
            [
                'id' => 5,
                'slug' => 'restaurant-pos',
                'title' => 'Sistem Kasir Restoran (POS)',
                'client' => 'Kopi Senja Nusantara',
                'client_industry' => 'Food & Beverage (F&B)',
                'duration' => 'Oktober 2023 - Desember 2023 (3 Bulan)',
                'category' => 'Custom Web App',
                'description' => 'Sistem kasir digital dengan manajemen meja, tampilan dapur realtime, dan pelacakan pesanan otomatis.',
                'overview' => 'Solusi Point of Sale (POS) berbasis cloud untuk cafe dan restoran. Memungkinkan pelayan mengambil pesanan langsung via tablet/HP, dapur menerima tiket order secara realtime, dan manajemen memantau omset harian.',
                'key_features' => [
                    'Point of Sale (POS) Layar Sentuh',
                    'Kitchen Display System (KDS) Realtime',
                    'Manajemen Layout Meja Restoran',
                    'Laporan Penjualan & Stok Bahan Baku'
                ],
                'gallery' => [
                    ['title' => 'Layar Kasir POS', 'image_url' => '/uploads/1781526616429-46906960-12.png'],
                    ['title' => 'Manajemen Layout Meja', 'image_url' => '/uploads/1781526251754-169158715-9.png'],
                    ['title' => 'Laporan Omset Harian', 'image_url' => '/uploads/1781527358962-872605838-15.png'],
                    ['title' => 'Stok & Inventaris Bahan', 'image_url' => '/uploads/1781526703401-819330083-13.png'],
                ],
                'image_url' => '/uploads/1781526616429-46906960-12.png',
                'live_url' => 'https://demo.juangdev.com/pos',
                'technologies' => ['Laravel', 'Alpine.js', 'MySQL', 'WebSockets'],
                'featured' => false,
                'is_boilerplate' => true,
                'sold_count' => 2,
                'package_tier' => 'Basic',
                'display_order' => 5,
            ],
            [
                'id' => 6,
                'slug' => 'construction-dashboard',
                'title' => 'Dashboard Proyek Konstruksi',
                'client' => 'BuildPro Construction',
                'client_industry' => 'Construction & Engineering',
                'duration' => 'Januari 2024 - April 2024 (4 Bulan)',
                'category' => 'Custom Web App',
                'description' => 'Dashboard manajemen proyek konstruksi untuk alokasi sumber daya, manajemen material, dan pelacakan progres lapangan.',
                'overview' => 'Aplikasi monitoring proyek bangunan dan insfrastruktur. Membantu Manajer Proyek memantau kurva-S progres pengerjaan, penggunaan anggaran material, absensi pekerja lapangan, serta log pengiriman alat berat.',
                'key_features' => [
                    'Visualisasi Kurva-S Progres Proyek',
                    'Manajemen Budgeting & Material',
                    'Laporan Harian Pekerja Lapangan',
                    'Dokumentasi Foto Progres Berkelanjutan'
                ],
                'gallery' => [
                    ['title' => 'Overview Progres Proyek', 'image_url' => '/uploads/1781526703401-819330083-13.png'],
                    ['title' => 'Manajemen Anggaran Material', 'image_url' => '/uploads/1781527358962-872605838-15.png'],
                    ['title' => 'Absensi Pekerja Lapangan', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                    ['title' => 'Dokumentasi Progres', 'image_url' => '/uploads/1781526860110-978453413-15.png'],
                ],
                'image_url' => '/uploads/1781526703401-819330083-13.png',
                'live_url' => 'https://demo.juangdev.com/construction',
                'technologies' => ['Laravel', 'Tailwind CSS', 'Chart.js', 'Docker'],
                'featured' => false,
                'is_boilerplate' => true,
                'sold_count' => 1,
                'package_tier' => 'Premium',
                'display_order' => 6,
            ],
            [
                'id' => 7,
                'slug' => 'travel-booking-system',
                'title' => 'Sistem Reservasi Tour & Travel',
                'client' => 'Jelajah Tour & Travel',
                'client_industry' => 'Tourism & Travel Agency',
                'duration' => 'Mei 2024 - Juli 2024 (3 Bulan)',
                'category' => 'Landing Page',
                'description' => 'Platform biro perjalanan wisata online dengan pemesanan hotel, tiket pesawat, paket tour, dan integrasi pembayaran.',
                'overview' => 'Website portal wisata interaktif yang menyajikan paket liburan domestik dan internasional. Pengunjung dapat memilih tanggal, jumlah orang, melakukan booking instan, dan membayar melalui QRIS atau transfer bank.',
                'key_features' => [
                    'Katalog Paket Tour Interaktif',
                    'Form Booking & Kalender Ketersediaan',
                    'Integrasi Gateway Pembayaran QRIS',
                    'E-Voucher & Tiket PDF Otomatis'
                ],
                'gallery' => [
                    ['title' => 'Halaman Katalog Paket Tour', 'image_url' => '/uploads/1781526786919-43514709-14.png'],
                    ['title' => 'Form Booking & Tanggal', 'image_url' => '/uploads/1781526529261-225644737-11.png'],
                    ['title' => 'Integrasi Checkout QRIS', 'image_url' => '/uploads/1781526941397-658466739-16.png'],
                    ['title' => 'Generasi E-Voucher PDF', 'image_url' => '/uploads/1781526616429-46906960-12.png'],
                ],
                'image_url' => '/uploads/1781526786919-43514709-14.png',
                'live_url' => 'https://demo.juangdev.com/travel',
                'technologies' => ['Laravel', 'MySQL', 'Midtrans', 'Tailwind CSS'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 1,
                'package_tier' => 'Basic',
                'display_order' => 7,
            ],
            [
                'id' => 8,
                'slug' => 'saas-startup-landing',
                'title' => 'SaaS & App Startup Landing Page',
                'client' => 'CloudSync Technologies',
                'client_industry' => 'Software & SaaS Startup',
                'duration' => 'Juni 2024 (2 Minggu)',
                'category' => 'Landing Page',
                'description' => 'Landing page teknologi tinggi dengan konversi cepat, showcase fitur interaktif, tabel perbandingan harga, dan integrasi checkout.',
                'overview' => 'Template landing page dirancang presisi untuk memvalidasi produk SaaS, aplikasi mobile, atau software B2B secara instan dengan desain modern dan performa super kilat.',
                'key_features' => [
                    'Hero Section Interaktif dengan Demo Video/Mockup',
                    'Pricing Comparison Matrix & Toggle Bulanan/Tahunan',
                    'Social Proof Testimonial Carousel',
                    'Form Lead Capture Terintegrasi WhatsApp'
                ],
                'gallery' => [
                    ['title' => 'Hero Banner SaaS', 'image_url' => '/uploads/1781526251754-169158715-9.png'],
                    ['title' => 'Tabel Harga Komparatif', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                ],
                'image_url' => '/uploads/1781526251754-169158715-9.png',
                'live_url' => 'https://demo.juangdev.com/saas-landing',
                'technologies' => ['Blade', 'Tailwind CSS', 'Alpine.js'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 4,
                'package_tier' => 'Basic',
                'display_order' => 8,
            ],
            [
                'id' => 9,
                'slug' => 'creative-agency-landing',
                'title' => 'Creative Studio & Agency Landing',
                'client' => 'Artisan Media Group',
                'client_industry' => 'Creative & Marketing Agency',
                'duration' => 'Juli 2024 (3 Minggu)',
                'category' => 'Landing Page',
                'description' => 'Landing page eksklusif dengan estetika gelap modern, micro-interactions, portfolio showcase masonry, dan form kontak brief.',
                'overview' => 'Dirancang untuk agensi kreatif, studio foto, atau konsultan branding yang membutuhkan website dengan visual berkelas dan konversi lead tinggi.',
                'key_features' => [
                    'Showcase Portfolio Masonry Interaktif',
                    'Micro-Animations & Smooth Scrolling',
                    'Client Logo Cloud & Case Study Section',
                    'Formulir Brief Proyek Interaktif'
                ],
                'gallery' => [
                    ['title' => 'Showcase Agency', 'image_url' => '/uploads/1781526860110-978453413-15.png'],
                    ['title' => 'Case Study Grid', 'image_url' => '/uploads/1781526529261-225644737-11.png'],
                ],
                'image_url' => '/uploads/1781526860110-978453413-15.png',
                'live_url' => 'https://demo.juangdev.com/agency-landing',
                'technologies' => ['Laravel', 'Tailwind CSS', 'GSAP'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 3,
                'package_tier' => 'Rekomendasi',
                'display_order' => 9,
            ],
            [
                'id' => 10,
                'slug' => 'ecommerce-fashion-store',
                'title' => 'Fashion & Apparel Online Store',
                'client' => 'Fashion Outlet ID',
                'client_industry' => 'Retail & E-Commerce',
                'duration' => 'Februari 2024 - Juni 2024 (5 Bulan)',
                'category' => 'E-Commerce',
                'description' => 'Toko online multi-vendor dengan manajemen stok barang, pemrosesan pesanan otomatis, dan dashboard analitik penjualan.',
                'overview' => 'Toko online fashion berperforma tinggi yang dibangun untuk pengalaman belanja mulus di smartphone. Dilengkapi keranjang belanja, voucher diskon, hitung ongkir otomatis JNE/TIKI/POS, dan notifikasi resi pengiriman.',
                'key_features' => [
                    'Katalog Produk & Variansi Ukuran/Warna',
                    'Cek Ongkir Otomatis Kurir Indonesia',
                    'Payment Gateway (QRIS, VA, E-Wallet)',
                    'Dashboard Admin Penjualan & Resi'
                ],
                'gallery' => [
                    ['title' => 'Katalog Produk Fashion', 'image_url' => '/uploads/1781526860110-978453413-15.png'],
                    ['title' => 'Keranjang & Checkout', 'image_url' => '/uploads/1781526786919-43514709-14.png'],
                ],
                'image_url' => '/uploads/1781526941397-658466739-16.png',
                'live_url' => 'https://demo.juangdev.com/store',
                'technologies' => ['Laravel', 'Blade', 'MySQL', 'Midtrans'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 2,
                'package_tier' => 'Basic',
                'display_order' => 10,
            ],
            [
                'id' => 11,
                'slug' => 'corporate-modern-profile',
                'title' => 'Corporate & Business Profile',
                'client' => 'PT Sinergi Dinamika Abadi',
                'client_industry' => 'Corporate & Holding Company',
                'duration' => 'April 2024 (3 Minggu)',
                'category' => 'Company Profile',
                'description' => 'Website profil perusahaan profesional dengan tata letak elegan, profil tim eksekutif, sertifikasi perusahaan, dan laporan tahunan.',
                'overview' => 'Template Company Profile berstandar korporat yang memberikan kredibilitas instan di mata investor, mitra B2B, dan calon klien institusi.',
                'key_features' => [
                    'Tata Letak Multi-Halaman Responsif',
                    'Visi Misi & Struktur Dewan Direksi',
                    'Galeri Proyek & Portofolio Klien',
                    'Download Brosur & Company Profile PDF'
                ],
                'gallery' => [
                    ['title' => 'Corporate Home', 'image_url' => '/uploads/1781526616429-46906960-12.png'],
                    ['title' => 'Struktur Manajemen', 'image_url' => '/uploads/1781526703401-819330083-13.png'],
                ],
                'image_url' => '/uploads/1781526616429-46906960-12.png',
                'live_url' => 'https://demo.juangdev.com/corporate',
                'technologies' => ['Laravel', 'Blade', 'Tailwind CSS'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 5,
                'package_tier' => 'Basic',
                'display_order' => 11,
            ],
            [
                'id' => 12,
                'slug' => 'law-firm-profile',
                'title' => 'Law Firm & Legal Consultant Profile',
                'client' => 'Pradana & Partners Law Firm',
                'client_industry' => 'Legal & Advocacy Services',
                'duration' => 'Mei 2024 (1 Bulan)',
                'category' => 'Company Profile',
                'description' => 'Website profil firma hukum berkelas dengan katalog bidang praktik (practice areas), profil advokat senior, dan sistem booking konsultasi.',
                'overview' => 'Menghadirkan citra otoritatif dan terpercaya untuk advokat, notaris, konsultan pajak, atau kantor akuntan publik.',
                'key_features' => [
                    'Katalog Area Praktik Hukum Detail',
                    'Profil Advokat & Riwayat Kasus',
                    'Formulir Permintaan Konsultasi Hukum',
                    'Artikel & Opini Hukum Blog'
                ],
                'gallery' => [
                    ['title' => 'Practice Areas', 'image_url' => '/uploads/1781526703401-819330083-13.png'],
                    ['title' => 'Advocate Directory', 'image_url' => '/uploads/1781526353116-173345013-10.png'],
                ],
                'image_url' => '/uploads/1781526703401-819330083-13.png',
                'live_url' => 'https://demo.juangdev.com/lawfirm',
                'technologies' => ['Laravel', 'Blade', 'MySQL', 'Tailwind CSS'],
                'featured' => true,
                'is_boilerplate' => true,
                'sold_count' => 2,
                'package_tier' => 'Rekomendasi',
                'display_order' => 12,
            ],
        ];
        foreach ($portfolios as $port) {
            Portfolio::create($port);
        }

        // 8. Testimonials (Dedicated TestimonialSeeder)
        $this->call(TestimonialSeeder::class);

        // 9. Blogs (10 items)
        Blog::truncate();
        $blogs = [
            [
                'id' => 1,
                'title' => 'Mengapa Laravel & PHP Modern adalah Solusi Web Terbaik di 2026',
                'slug' => 'laravel-future-2026',
                'excerpt' => 'Pelajari bagaimana Laravel dengan Blade, Alpine.js, dan Tailwind CSS menghadirkan performa cepat, keamanan tinggi, dan biaya perawatan hemat untuk bisnis Anda.',
                'content' => "Dalam era digital saat ini, kecepatan dan keandalan website merupakan faktor penentu keberhasilan bisnis. Laravel 11 hadir dengan arsitektur yang sangat efisien, integrasi database MySQL yang solid, serta ekosistem yang matang untuk mendukung pertumbuhan bisnis mulai dari startup hingga korporasi besar.\n\nKeunggulan utama teknologi ini meliputi fleksibilitas pengembangan, sistem autentikasi yang sangat aman, dan performa tinggi yang mampu menangani jutaan permintaan pengunjung setiap harinya.",
                'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
                'category' => 'Technology',
                'author' => 'Tim JuangDev',
                'read_time' => '5 mnt baca',
                'published_at' => now()->subDays(1),
                'is_published' => true,
            ],
            [
                'id' => 2,
                'title' => '10 Fitur Wajib yang Harus Ada di Website E-Commerce Modern',
                'slug' => 'ecommerce-essential-features',
                'excerpt' => 'Dari alur checkout instan hingga rekomendasi produk — ketahui fitur kunci yang membuat toko online sukses menghasilkan transaksi tinggi.',
                'content' => "Membangun toko online tidak hanya sekedar memajang foto produk. Diperlukan alur checkout yang mulus, integrasi gateway pembayaran otomatis, notifikasi WhatsApp realtime, serta kecepatan loading halaman yang optimal agar pengunjung nyaman bertransaksi.\n\nBeberapa fitur wajib yang direkomendasikan antara lain: perhitungan ongkos kirim otomatis (JNE/TIKI/POS), pilihan metode pembayaran QRIS & E-Wallet, serta sistem manajemen stok terpusat.",
                'image_url' => 'https://images.unsplash.com/photo-1556742049-0a67e5572263?w=600&auto=format&fit=crop&q=80',
                'category' => 'E-Commerce',
                'author' => 'Tim JuangDev',
                'read_time' => '7 mnt baca',
                'published_at' => now()->subDays(3),
                'is_published' => true,
            ],
            [
                'id' => 3,
                'title' => 'Bagaimana AI Mengubah Otomatisasi Bisnis & Layanan Pelanggan',
                'slug' => 'ai-business-automation',
                'excerpt' => 'Jelajahi bagaimana chatbot berbasis AI dan analitik prediktif membantu bisnis menghemat waktu dan biaya operasional.',
                'content' => "Customer service berbasis AI kini mampu menjawab pertanyaan pelanggan secara cerdas dan kontekstual 24 jam nonstop. Dengan integrasi AI pada website JuangDev, konsultasi kebutuhan website kini dapat dilakukan secara instan tanpa perlu menunggu balasan manual.",
                'image_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&auto=format&fit=crop&q=80',
                'category' => 'AI & Automation',
                'author' => 'Tim JuangDev',
                'read_time' => '6 mnt baca',
                'published_at' => now()->subDays(5),
                'is_published' => true,
            ],
            [
                'id' => 4,
                'title' => 'Pentingnya Desain UI/UX & Responsive Web untuk Konversi Bisnis',
                'slug' => 'importance-of-ui-ux-design',
                'excerpt' => 'Antarmuka intuitif dan tata letak responsif merupakan kunci utama mengubah pengunjung biasa menjadi pelanggan setia.',
                'content' => "Studi menunjukkan bahwa 88% pengguna tidak akan kembali ke website yang sulit diakses di smartphone. Oleh karena itu, penerapan desain UI/UX berbasis User-Centric Design sangat vital untuk memastikan navigasi website terasa cepat, responsif, dan menyenangkan.",
                'image_url' => 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=600&auto=format&fit=crop&q=80',
                'category' => 'Web Design',
                'author' => 'Tim JuangDev',
                'read_time' => '4 mnt baca',
                'published_at' => now()->subDays(7),
                'is_published' => true,
            ],
            [
                'id' => 5,
                'title' => 'Panduan Lengkap Memilih Jasa Pembuatan Website Profesional',
                'slug' => 'guide-choosing-web-agency',
                'excerpt' => 'Tips penting sebelum menyewa pengembang web agar investasi digital bisnis Anda memberikan hasil optimal dan terukur.',
                'content' => "Memilih mitra pengembang website bukan sekadar mencari harga termurah, melainkan mencari tim berpengalaman yang memahami alur bisnis Anda. Pastikan vendor pilihan Anda menyediakan transparansi kode, dukungan garansi maintenance, serta infrastruktur server yang aman.",
                'image_url' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
                'category' => 'Business Strategy',
                'author' => 'Tim JuangDev',
                'read_time' => '5 mnt baca',
                'published_at' => now()->subDays(9),
                'is_published' => true,
            ],
            [
                'id' => 6,
                'title' => 'Strategi SEO Lanjutan Agar Website Tampil di Halaman Pertama Google',
                'slug' => 'seo-optimization-tips-2026',
                'excerpt' => 'Pelajari teknik optimasi mesin pencari on-page dan teknik teknis agar website bisnis Anda mudah ditemukan calon pembeli.',
                'content' => "Search Engine Optimization (SEO) adalah strategi jangka panjang terbaik untuk mendatangkan lalu lintas organik tanpa harus bergantung terus-menerus pada iklan berbayar. Mulai dari keyword research, optimasi struktur URL, meta tag presisi, hingga kecepatan akses server.",
                'image_url' => 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&auto=format&fit=crop&q=80',
                'category' => 'Technology',
                'author' => 'Tim JuangDev',
                'read_time' => '6 mnt baca',
                'published_at' => now()->subDays(11),
                'is_published' => true,
            ],
            [
                'id' => 7,
                'title' => 'Panduan Integrasi Gateway Pembayaran Otomatis QRIS & E-Wallet',
                'slug' => 'payment-gateway-integration-guide',
                'excerpt' => 'Tingkatkan angka penjualan toko online dengan menyediakan metode pembayaran otomatis terlengkap di Indonesia.',
                'content' => "Pelanggan saat ini menyukai kemudahan transaksi instan melalui Scan QRIS, ShopeePay, GoPay, OVO, maupun Virtual Account bank. Mengintegrasikan Payment Gateway seperti Midtrans atau Xendit ke website e-commerce Anda akan meminimalisir transaksi terbengkalai.",
                'image_url' => 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&auto=format&fit=crop&q=80',
                'category' => 'E-Commerce',
                'author' => 'Tim JuangDev',
                'read_time' => '5 mnt baca',
                'published_at' => now()->subDays(13),
                'is_published' => true,
            ],
            [
                'id' => 8,
                'title' => 'Langkah Penting Menjaga Keamanan Website & Data Pelanggan Anda',
                'slug' => 'cybersecurity-best-practices',
                'excerpt' => 'Lindungi bisnis dan kepercayaan konsumen dari ancaman peretasan, malware, dan kebocoran data tersembunyi.',
                'content' => "Keamanan jaringan dan aplikasi web harus menjadi prioritas utama. Menggunakan enkripsi SSL/TLS, proteksi terhadap serangan SQL Injection & XSS, serta melakukan backup otomatis berkala adalah langkah proteksi wajib untuk setiap platform bisnis.",
                'image_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&auto=format&fit=crop&q=80',
                'category' => 'Technology',
                'author' => 'Tim JuangDev',
                'read_time' => '6 mnt baca',
                'published_at' => now()->subDays(15),
                'is_published' => true,
            ],
            [
                'id' => 9,
                'title' => 'Cara Mengoptimalkan Kecepatan Loading Website Hingga Skor 99+',
                'slug' => 'speed-optimization-website',
                'excerpt' => 'Kecepatan loading di bawah 2 detik meningkatkan kenyamanan pengunjung dan mendongkrak skor SEO Google.',
                'content' => "Kecepatan muat halaman dipengaruhi oleh kompresi format gambar (WebP/AVIF), minifikasi file CSS & JavaScript, pemanfaatan browser caching, serta penggunaan Content Delivery Network (CDN) yang tepat.",
                'image_url' => 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80',
                'category' => 'Web Design',
                'author' => 'Tim JuangDev',
                'read_time' => '5 mnt baca',
                'published_at' => now()->subDays(18),
                'is_published' => true,
            ],
            [
                'id' => 10,
                'title' => 'Transformasi Digital UMKM: Dari Usaha Konvensional Ke Pasar Global',
                'slug' => 'digital-transformation-smb',
                'excerpt' => 'Kisah dan panduan praktis bagaimana pemilik bisnis lokal mampu menjangkau ribuan pembeli baru melalui ekosistem digital.',
                'content' => "Digitalisasi bukan lagi pilihan melainkan kebutuhan mutlak untuk bertahan dan berkembang. Dengan memiliki website resmi yang kredibel, UMKM dapat membangun branding profesional dan melakukan penjualan secara otomatis tanpa batas geografis.",
                'image_url' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80',
                'category' => 'Business Strategy',
                'author' => 'Tim JuangDev',
                'read_time' => '4 mnt baca',
                'published_at' => now()->subDays(20),
                'is_published' => true,
            ],
        ];
        foreach ($blogs as $b) {
            Blog::create($b);
        }

        // 7. FAQs
        Faq::truncate();
        $faqItems = [
            [
                'question' => 'Berapa lama waktu pengerjaan website?',
                'answer' => 'Estimasi pengerjaan tergantung pada kompleksitas proyek. Landing page memerlukan waktu 2-3 hari, website company profile 3-7 hari, aplikasi web 2-4 minggu, dan sistem e-commerce/ERP 3-6 minggu. Kami akan memberikan lini masa yang jelas pada tahap awal.',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'question' => 'Berapa biaya pembuatan website di JuangDev?',
                'answer' => 'Biaya layanan kami sangat terjangkau mulai dari 99K untuk landing page dasar. Company profile berkisar dari 199K-499K, dan aplikasi web kustom mulai dari 999K+, tergantung pada fitur dan kompleksitas. Kami memberikan transparansi harga 100% tanpa biaya tersembunyi.',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'question' => 'Apakah bisa melakukan redesain website yang sudah ada?',
                'answer' => 'Tentu saja! Kami berpengalaman dalam melakukan redesain, perbaikan tampilan, dan modernisasi website. Kami akan menganalisis website Anda saat ini, meningkatkan kecepatan, pengalaman pengguna, serta kenyamanan di perangkat seluler dengan tetap mempertahankan identitas brand Anda.',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'question' => 'Apakah JuangDev menyediakan garansi dan dukungan purna jual?',
                'answer' => 'Ya! Seluruh layanan kami sudah mencakup dukungan purna jual (mulai dari 30 hari hingga perawatan berkala). Kami juga membantu pengaturan domain, hosting, pembaruan keamanan, dan penambahan fitur.',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'question' => 'Teknologi apa saja yang digunakan?',
                'answer' => 'Kami menggunakan teknologi modern dan andal: Laravel, Blade, Tailwind CSS, Alpine.js, MySQL untuk website render server yang super cepat, serta Next.js dan REST API untuk aplikasi web kustom yang kompleks.',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'question' => 'Bagaimana sistem pembayarannya?',
                'answer' => 'Kami menggunakan struktur pembayaran yang aman dan transparan: Down Payment (DP) sebesar 50% untuk memulai pengerjaan, dan pelunasan sisa 50% setelah proyek selesai diuji dan siap diserahterimakan.',
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'question' => 'Apakah bisa meminta fitur kustom atau integrasi khusus?',
                'answer' => 'Tentu saja! Pengembangan fitur kustom adalah keahlian utama kami. Baik itu Payment Gateway (Midtrans/Xendit), notifikasi WhatsApp otomatis, dashboard analitik kustom, chatbot AI, atau logika bisnis unik — kami akan membangun sesuai kebutuhan Anda.',
                'display_order' => 7,
                'is_active' => true,
            ],
        ];
        foreach ($faqItems as $f) {
            Faq::create($f);
        }

        // 8. Process Steps (Cara Pemesanan)
        ProcessStep::truncate();
        $steps = [
            [
                'step_number' => '01',
                'icon' => 'monitor',
                'title' => 'Konsultasi & Penentuan Kebutuhan',
                'description' => 'Sampaikan kebutuhan bisnis Anda, mulai dari jenis platform yang ingin dibangun, fitur utama yang dibutuhkan, hingga target pengunjung yang ingin dicapai.',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'step_number' => '02',
                'icon' => 'lightbulb',
                'title' => 'Rekomendasi Solusi & Paket',
                'description' => 'Tim kami akan menganalisis kebutuhan Anda dan menyarankan jenis website/aplikasi serta paket investasi yang paling efektif dan efisien untuk bisnis Anda.',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'step_number' => '03',
                'icon' => 'handshake',
                'title' => 'Kesepakatan & Pengumpulan Data',
                'description' => 'Setelah menyetujui proposal, Anda melakukan Down Payment (DP) 50%. Selanjutnya, Anda memberikan informasi lengkap dan aset (logo, teks, foto) yang ingin ditampilkan.',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'step_number' => '04',
                'icon' => 'rocket',
                'title' => 'Pengerjaan & Serah Terima',
                'description' => 'Kami memproses pengerjaan dengan pembaruan berkala. Setelah proyek selesai diuji dan disetujui, Anda melunasi sisa 50% sebelum website diserahterimakan secara penuh.',
                'display_order' => 4,
                'is_active' => true,
            ],
        ];
        foreach ($steps as $s) {
            ProcessStep::create($s);
        }
    }
}
